<?php

namespace Nmc\DynamicPageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository implements PageProviderInterface
{
    /**
     * @param int $websiteId
     * @return Page[]
     */
    public function getPagesByWebsiteId($websiteId)
    {
        return $this->findBy(array('websiteId' => $websiteId));
    }

}
