parameters:
    nmc_dynamic_page.default.action: Nmc\DynamicPageBundle\Controller\DefaultController::pageAction

services:

    nmc.dynamic_website.listener.request_listener:
        class: Nmc\DynamicPageBundle\Listener\RequestLocalListener
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    nmc_dynamic_page.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - NmcDynamicPageBundle:Page

    nmc_dynamic_page.page_of_web_provider:
        class: Nmc\DynamicPageBundle\Entity\PageOfWebsiteProvider
        arguments: [@nmc_dynamic_page.repository, "@=service('nmc.dynamic_website.web_finder').getWebsite().getId()"]

    nmc_dynamic_page.page_provider:
        class: Nmc\DynamicPageBundle\Entity\PageProvider
        arguments: [@nmc_dynamic_page.repository]


    nmc_dynamic_page.router:
        class: Nmc\DynamicPageBundle\Routing\RouteProvider
        arguments: [@nmc_dynamic_page.provider_service_id, '%nmc_dynamic_page.default.action%']


    nmc_dynamic_page.menu_builder:
        class: Nmc\DynamicPageBundle\Menu\Builder
        arguments: [@knp_menu.factory, @nmc_dynamic_page.provider_service_id]

    nmc_dynamic_page.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: nmc_dynamic_page.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: dynamicPageMenu } # The alias is what is used to retrieve the menu