parameters:
#    nmc_dynamic_page.example.class: Nmc\DynamicPageBundle\Example

services:
#    nmc_dynamic_page.example:
#        class: %nmc_dynamic_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    kernel.listener.request_listener:
        class: Nmc\DynamicPageBundle\Listener\RequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    nmc.dynamic_page.web_finder:
        class: Nmc\DynamicPageBundle\Routing\WebsiteFinder
        arguments: [@request_stack, @nmc.website.repository ]

    nmc.dynamic_page.router:
        class: Nmc\DynamicPageBundle\Routing\RouteProvider
        arguments: [@nmc.dynamic_page.web_finder]

    nmc.website.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - NmcDynamicPageBundle:Website

    nmc.dynamic_page.menu_builder:
        class: Nmc\DynamicPageBundle\Menu\Builder
        arguments: [@knp_menu.factory, @nmc.dynamic_page.web_finder]

    nmc.dynamic_page.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: nmc.dynamic_page.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: dynamicPageMenu } # The alias is what is used to retrieve the menu