parameters:
#    nmc_dynamic_page.example.class: Nmc\DynamicPageBundle\Example

services:
#    nmc_dynamic_page.example:
#        class: %nmc_dynamic_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    kernel.listener.request_listener:
        class: Nmc\DynamicPageBundle\Listener\RequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request }
    nmc.dynamic_page.router:
        class: Nmc\DynamicPageBundle\Routing\RouteProvider